[general]
import = ["themes/modus_vivendi.toml"]

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[font]
size = 15

[font.normal]
family = "CommitMono Nerd Font"

[keyboard]
bindings = [
    { key="C", mods="Control|Shift", action="Copy" },
    { key="V", mods="Control|Shift", action="Paste" }
]

[window.dimensions]
columns = 120
lines = 30

